default_platform(:ios)

app_name              = 'ReactNativeTest'
team_id               = ENV["FASTLANE_TEAM_ID"]
cert                  = ENV["APPLE_CERT"]
key                   = ENV["APPLE_KEY"]
key_pwd               = ENV["APPLE_KEY_PASSWORD"]
appstore_key_id       = ENV["APP_STORE_CONNECT_API_KEY_ID"]
appstore_issuer_id    = ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"]
appstore_key_filepath = ENV["APP_STORE_CONNECT_API_KEY_FILE_PATH"]

platform :ios do

  lane :set_signing do
    setup_ci(
      force: true,
      provider: "travis"
    )

    unlock_keychain(
      path: "fastlane_tmp_keychain",
      password: "",
      set_default: true
    )

    import_certificate(
      certificate_path: key,
      certificate_password: key_pwd,
      keychain_name: "fastlane_tmp_keychain",
      keychain_password: "",
      log_output: true
    )

    import_certificate(
      certificate_path: cert,
      keychain_name: "fastlane_tmp_keychain",
      keychain_password: "",
      log_output: true
    )
  end

  lane :build_and_sign do |options|
    set_signing
    cocoapods
    gym(
      scheme: options[:scheme],
      workspace: app_name+'.xcworkspace',
      export_method: options[:method],
      export_options: {iCloudContainerEnvironment: 'Production'},
      clean: true,
      include_bitcode: true,
      output_name: options[:scheme]+".ipa",
      export_team_id: team_id,
      configuration: 'Prod'
    )
  end

  lane :build_ios do
    build_and_sign(
      scheme: app_name,
      method: 'ad-hoc'
    )
  end

  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: appstore_key_id,
      issuer_id: appstore_issuer_id,
      key_filepath: appstore_key_filepath,
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

end
