default_platform(:android)

platform :android do
    desc "Deploy an alpha version to Google Play"
    lane :alpha do
        gradle(task: "bundleProdRelease")
        upload_to_play_store(track: "alpha")
    end
end
