name: Release Android - Production

on:
  release:
    types: [ published ]

env:
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
  KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
  ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
  PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}

jobs:
  android-prod-publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        run: chmod +x android/gradlew

      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > release.keystore.jks.b64
          base64 -d -i release.keystore.jks.b64 > app/release.keystore.jks
        working-directory: android

      - name: Build bundle android
        run: npm run bundle-android-prod

      - name: Create Google Play Config file
        run: |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        working-directory: android

      - name: Validate Google Play Store json_key works
        run: fastlane run validate_play_store_json_key json_key:play_config.json
        working-directory: android

      - name: Distribute app to alpha track 🚀
        if: ${{ github.event.release.prerelease }}
        run: |
          EXTRACTED_VERSION=$(awk -F \" '/"version": ".+"/ { print $4; exit; }' ../package.json)
          export VERSION_CODE=${{ github.run_number }}
          export VERSION_NAME="$EXTRACTED_VERSION-${{ github.run_number }}"
          fastlane alpha
        working-directory: android

      - name: Distribute app  🚀
        if: ${{ !github.event.release.prerelease }}
        run: |
          EXTRACTED_VERSION=$(awk -F \" '/"version": ".+"/ { print $4; exit; }' ../package.json)
          export VERSION_CODE=${{ github.run_number }}
          export VERSION_NAME="$EXTRACTED_VERSION-${{ github.run_number }}"
          fastlane production
        working-directory: android
