name: Release Android Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version: patch | minor | major'
        required: true
      release:
        description: 'Version type alpha | beta | prod'
        required: true

jobs:
  android-version-bump:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Version bump and tagging
        run: |
          npm ci
          npm version ${{ github.event.inputs.version }}
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}

#  android-prod-publish:
#    needs: android-version-bump
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@master
#
#      - name: Cache Gradle
#        uses: actions/cache@v1
#        with:
#          path: ~/.gradle/caches/
#          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}
#
#      - name: Cache Gradle Wrapper
#        uses: actions/cache@v1
#        with:
#          path: ~/.gradle/wrapper/
#          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}
#
#      - name: Grant Permission to Execute
#        run: chmod +x android/gradlew
#
#      - name: Configure Keystore
#        run: |
#          echo "$ANDROID_KEYSTORE_FILE" > android/release.keystore.jks.b64
#          base64 -d -i android/release.keystore.jks.b64 > android/app/release.keystore.jks
#        env:
#          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
#
#      - name: Build bundle android
#        run: |
#          npm run bundle-android-prod
#
#      - name: Create Google Play Config file
#        run: |
#          echo "$PLAY_CONFIG_JSON" > android/play_config.json.b64
#          base64 -d -i android/play_config.json.b64 > android/play_config.json
#        env:
#          PLAY_CONFIG_JSON: ${{ secrets.GOOGLE_PLAY_CONFIG_JSON }}
#
#      - name: Validate Google Play Store json_key works
#        run: |
#          (cd android && bundle exec fastlane run validate_play_store_json_key json_key:play_config.json)
#
#      - name: Distribute app to alpha  🚀
#        run: |
#          (cd android && bundle exec fastlane ${{ github.event.inputs.release }})
#        env:
#          KEYSTORE_KEY_ALIAS: ${{ secrets.GOOGLE_STORE_KEY_ALIAS }}
#          KEYSTORE_KEY_PASSWORD: ${{ secrets.GOOGLE_STORE_KEY_PASSWORD }}
#          KEYSTORE_STORE_PASSWORD: ${{ secrets.GOOGLE_STORE_PASSWORD }}
