name: Release iOS - Production

on:
  release:
    types:
     - created

jobs:
  prJob:
    name: Print info
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "event type is:" ${{ github.event.action }}
          echo "prerelease:" ${{ github.event.release.prerelease }}
